const CartActionTypes = {
    TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
    ADD_ITEMS: 'ADD_ITEMS',
    REMOVE_ITEMS: 'REMOVE_ITEMS',
    WITHDRAW_ITEM: 'WITHDRAW_ITEM',
    APPEND_ITEM: 'APPEND_ITEM',
    CLEAR_CART: 'CLEAR_CART'
};

export default CartActionTypes;